// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMe8hPL9_ByQ8wr_usiy7eqoGJZH5Y_w0',
    appId: '1:113360283838:web:7a028eaefce3fbb71516ef',
    messagingSenderId: '113360283838',
    projectId: 'pizza-delivery-app-2fe83',
    authDomain: 'pizza-delivery-app-2fe83.firebaseapp.com',
    storageBucket: 'pizza-delivery-app-2fe83.appspot.com',
    measurementId: 'G-0HE67RQ6FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAybYux_PmOAjZk0eVQqXQwKt9UWb7wFzQ',
    appId: '1:113360283838:android:7410180a60978a331516ef',
    messagingSenderId: '113360283838',
    projectId: 'pizza-delivery-app-2fe83',
    storageBucket: 'pizza-delivery-app-2fe83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxqaBV50fhzw9_L2-srkGyCzX4B3YNSSY',
    appId: '1:113360283838:ios:ba685adcc180ec491516ef',
    messagingSenderId: '113360283838',
    projectId: 'pizza-delivery-app-2fe83',
    storageBucket: 'pizza-delivery-app-2fe83.appspot.com',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxqaBV50fhzw9_L2-srkGyCzX4B3YNSSY',
    appId: '1:113360283838:ios:ba685adcc180ec491516ef',
    messagingSenderId: '113360283838',
    projectId: 'pizza-delivery-app-2fe83',
    storageBucket: 'pizza-delivery-app-2fe83.appspot.com',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMe8hPL9_ByQ8wr_usiy7eqoGJZH5Y_w0',
    appId: '1:113360283838:web:65eb3a6b3cb112ee1516ef',
    messagingSenderId: '113360283838',
    projectId: 'pizza-delivery-app-2fe83',
    authDomain: 'pizza-delivery-app-2fe83.firebaseapp.com',
    storageBucket: 'pizza-delivery-app-2fe83.appspot.com',
    measurementId: 'G-GHS9KFCWV1',
  );
}
